### ISSUE TITLE
Meaningful screenshot names

### ISSUE THREAD

**Issue by manevpe** [azachar/protractor-screenshoter-plugin#1]
Right now, screenshot names are uids - it would be better if they had the spec name as a prefix.

**Comment by azachar** [comment]
Dear @manevpe, 

Thank you for you feedback. You have a very valid question.

The uuid are there for several reasons - you suppose to use a report analyzer (that is bundled with this reporter) that takes your results from each of your expectation or spec including screenshots and console logs and visualize them, so you can get a holistic overview of your tests. Second uuid files names are portable between windows, linux, mac. On windows there are same limits with 255 length of the file. 

Third, it doens't make sense to use this tool and look under the hood on your own. Basically, you want to drive a car, nor naming pipes in the engine. If you do not want to use html reports and want to stick to screenshots without console logs, feel free to use other reporters that are more low level and without additional functionality, then of course naming screenshots makes sense.

I hope I answer your question.

Cheers,
Andrej
