### ISSUE TITLE
One screenshot per all tests in spec file

### ISSUE THREAD

**Issue by RatkoR** [azachar/protractor-screenshoter-plugin#11]
Hi, kudos for a great project.

I have multiple test files, for example:

```
/e2e/specs/articles.spec.ts
/e2e/specs/comments.spec.ts
/e2e/specs/users.spec.ts
```

each has multiple tests inside:

```
describe('Article', function() {
    it('should do something', function() {
        expect(...);
    });

    it('should do something', function() {
        expect(...);
    });

    it('should do something', function() {
        expect(...);
    });
```

As far as I see, screenshotOnSpec creates screenshot for every `it('...')` part. Is it possible to have only one screenshot per `describe('...')` part?

**Comment by azachar** [comment]
Hi there, 

In theory, it should be possible. It all depends on jasmine, as far as I see it, https://jasmine.github.io/2.5/custom_reporter.html, if you want you can help me to make such a feature. I would be very happy to review any PR with updated tests.

Cheers,
Andrej

**Comment by azachar** [comment]
Due to inactivity, I am closing this issue. If you feel that it should be open, please provide with updated PR. Thanks.
