### ISSUE TITLE
include html-snapshots option

### ISSUE THREAD

**Issue by dejwf** [azachar/protractor-screenshoter-plugin#14]
Hi , thanks a lot for this plugin!

 could you include html-snapshots in your plugin? It is very convenient for test development on more complex apps. Here is npm link: https://www.npmjs.com/package/html-snapshots

Thank you

**Comment by azachar** [comment]
Hi There, 

Thank you for your suggestion, I am still quite not sure what it does and how this fit into screenshoter. Could you please provide some scenarios? Thanks.

**Comment by azachar** [comment]
Hey @dejwf,
Thank you for your explanation, it makes a perfect sense to have such a feature. I think it should be implemented the same way as pictures are implemented. Also, the reporter project needs to be updated to reflect HTML snapshots.

This plugin should introduce new config variables called:

htmlSnapshotOnExpect: 
'failure' - makes a snapshot after each failure
'failure+success' -  makes a snapshot after each expects.
'none' - skip completely

Do you mind to provide the initial implementation?

Cheers,
Andrej

**Comment by azachar** [comment]
I implemented an initial version of raw HTML snapshots, have a look at https://github.com/azachar/protractor-screenshoter-plugin/tree/feat-html-snapshot

What needs to be done is the visualization of results - e.g. the https://github.com/azachar/screenshoter-report-analyzer  needs to be updated to show raw HTML file.

Have a look at it and let me know what do you think.

Cheers,
Andrej

**Comment by azachar** [comment]
As of release 0.8.0 HTML snapshots are supported.
