### ISSUE TITLE
npm release of 0.3.1

### ISSUE THREAD

**Issue by bratta** [azachar/protractor-screenshoter-plugin#15]
Hello,

This is a great tool. I could make use of version 0.3.1 but it hasn't made it to npm yet, apparently from a spec making the `npm test` step fail. Any idea on when this will be resolved?

**Comment by azachar** [comment]
Hello, 
the tests are failing on 0.3.1 so that is the reason, why it is not pushed to npm. 

The 0.3.0 is as good as 0.3.1, so you should be fine with it. The tests issue related to 0.3.1 will be fixed with the later release.

Hope, I helped!

Cheers,
Andrej

**Comment by azachar** [comment]
Actually, the build just passed (there is one flaky test that fails sometimes due to missing jasmine promises). So please go ahead with 0.3.1. and let me know if there are any other issues.

**Comment by bratta** [comment]
Thanks! I was able to pull down 0.3.1 from npm and it works great now. 👍
