### ISSUE TITLE
Ability to use an other html reporter that default one

### ISSUE THREAD

**Issue by matthieuh** [azachar/protractor-screenshoter-plugin#17]
Hi, first of all thanks a lot for this plugin !

A cool new feature could be to have ability to have a parameter to set our own html reporter.

I can help if you need to and if you can give some informations on how data is passed to this reporter.

**Comment by azachar** [comment]
Hi @matthieuh,

you can already do it, set `htmlReport: false`, and then use your HTML reporter.

The particular report files are generated in `/reports/*.js` folder and there is one top-level `/report.js` that contains all data from all particular reports. 

The file format can be learned from tests.

Btw. why do you need your own reporter?  If you miss something, let's improve the default one. 

Cheers, 
Andrej
