### ISSUE TITLE
Test won't fail on some Angular log errors

### ISSUE THREAD

**Issue by valburyakov** [azachar/protractor-screenshoter-plugin#18]
Hi there, thx for great reporter and I faced with strange issue if there is a log error test won't failed in spite of failTestOnErrorLog option:
Error: `http://localhost:9000/sales/cancel/24 - Failed to load resource: the server responded with a status of 500 (Internal Server Error)`. This error is only visible on 'Console reporter' tab and this test marked as passed.
[Screenshot reporter tab](http://imageshack.com/a/img922/1985/bWyia5.png)
[Console reporter tab](http://imageshack.com/a/img923/6132/f9UMv5.png)
But if we produce console error manually - then test fails:
`browser.executeScript('console.error("sample error")');` 
Plugin-config:
```
{
      package: 'protractor-screenshoter-plugin',
      screenshotPath: config.resultFolder + '/htmlreport',
      screenshotOnExpect: 'failure',
      screenshotOnSpec: 'failure+success',
      withLogs: true,
      failTestOnErrorLog: {
        failTestOnErrorLogLevel: 900,
        excludeKeywords: ['favicon.ico', '0/$compile/tpload?p0=public%2Fpartials%2Finvoices%2Flist.html']
      },
      writeReportFreq: 'spec',
      clearFoldersBeforeTest: false
    }
```
Chrome-options:
```
capabilities: {
    'browserName': 'chrome',
    loggingPrefs: {
      'driver': 'INFO',
      'browser': 'INFO'
    },
    'chromeOptions': {
      'args': ['--test-type', '--no-sandbox'],
      prefs: {
        'download': {
          "directory_upgrade": true,
          'prompt_for_download': false,
          'default_directory': path.resolve(__dirname, './downloads/'),
        },
      },
    }
```

**Comment by azachar** [comment]
Hey @valburyakov, 
thanks for your report, could you please also provide a sample spec that fails?
The feature that fails comes from the original fork, so I need more investigation to fix.

Cheers,
Andrej

**Comment by valburyakov** [comment]
I'm afraid i can't provide a spec because it's a flaky test and it's not stable and it's on our dev server. You can try to reproduce it with some angular app generating some server error manually and look if test will fail.

**Comment by azachar** [comment]
Sorry, have no time for that, please try to write a test - see the readme file how to write it. That way you can run it 100 times to see if it really happens.

Some of these errors come also from buggy web drivers. Perhaps this could be the one.
