### ISSUE TITLE
Can't install on windows because of install bug in lwipify

### ISSUE THREAD

**Issue by reppners** [azachar/protractor-screenshoter-plugin#29]
https://github.com/IonicaBizau/image-to-ascii/issues/49

Hope this gets fixed soon so I can use this plugin as its really helpful in tracking bugs down. Open as issue here to be a reminder to upgrade once the dependency releases a fix.

**Comment by reppners** [comment]
Fixed already :)

**Comment by azachar** [comment]
Thanks for reaching me with this issue. I am going to upgrade to a new version, then let me know, if it helps.

Cheers,
Andrej

**Comment by reppners** [comment]
Its already working because the dependency of the dependency is installed with a newer patch version :) Great plugin btw 👍

**Comment by azachar** [comment]
Great to hear that :)
