### ISSUE TITLE
After spec screenshots not showing on the report

### ISSUE THREAD

**Issue by manevpe** [azachar/protractor-screenshoter-plugin#3]
When the configuration has enabled after spec screenshots, they are properly done and exist in the screenshots folder, but they are not shown on the html report. On expect failure screenshots work normally, just the after spec ones are not showing.

**Comment by azachar** [comment]
Could you please provide your full configuration?  I mean, could you share your 

```
exports.config = {
      plugins: [{
        package: 'protractor-screenshoter-plugin',
        screenshotPath:'./REPORTS/e2e',
        screenshotOnExpect: 'failure+success',
        screenshotOnSpec: 'none',
        withLogs: 'true',
        htmlWriteFreq: 'asap',
        clearFoldersBeforeTest: true,
      }]
    };
```

**Comment by azachar** [comment]
Btw i just realized that the doc is wrong, there should be `writeReportFreq` instead `htmlWriteFreq`

**Comment by manevpe** [comment]
Here is my config:
```
plugins: [{
    package: 'protractor-screenshoter-plugin',
    screenshotPath:'./reports/integration/html-report',
    screenshotOnExpect: 'none',
    screenshotOnSpec: 'failure',
    htmlReport: true,
    withLogs: true,
    writeReportFreq: 'end',
    clearFoldersBeforeTest: false
  }],
```
I've also tried with screenshotOnExpect: 'failure' - same result - on spec failure are not shown on the report - only on expect failure do.
