### ISSUE TITLE
HTML report doesn't include all the specs it ran

### ISSUE THREAD

**Issue by smahalingam** [azachar/protractor-screenshoter-plugin#30]
<img width="1235" alt="screen shot 2017-04-01 at 01 00 00" src="https://cloud.githubusercontent.com/assets/6057889/24573081/a947efd6-1676-11e7-8bd9-e741df552b9b.png">

I had above configuration. ie., Total number of specs - 7 and 'maxInstances' is 2.  Once all the test is ran, only last 2 specs are present in the html report file. 
I tried increasing the 'maxInstances': 3 and this time i see 3 specs in the html report file. 

Is it expected Or am i doing some thing wrong ?

Thanks in Advance,
Shan

**Comment by azachar** [comment]
Hello @smahalingam, 
hmm, that is weird, perhaps there is an issue in the concurrency of the writing. Try to remove the option ``writeReportFreq`` or set it to ``end`` instead of ``asap``. Does it help?

Cheers,
Andrej

**Comment by smahalingam** [comment]
@azachar Thanks for your reply. I added 
```clearFoldersBeforeTest: false ``` and it works fine now. I have another script that deletes the folder before test starts.

**Comment by azachar** [comment]
Great to hear that, so I am closing the issue now :)
