### ISSUE TITLE
Include console output

### ISSUE THREAD

**Issue by ankitkumarr** [azachar/protractor-screenshoter-plugin#32]
Hi,

Is there a way to include the console output from the protractor tests in the report?

For example, if my tests are logging the time taken by certain events to complete, I would love to have them show in the report.

BTW, great plugin! Thank you for your work!

Ankit

**Comment by azachar** [comment]
Hello Ankit, 
that is an interesting question, I guess we should ask authors of protractor itself, whether we can grab after each expectation the output from protractor console, e.g. not from the test browsers instance, but from the protractor's terminal console itself, am I right?

If yes, then could you please ask this on gitter.com and link it with this issue?

Cheers,
Andrej

**Comment by ankitkumarr** [comment]
Hi Andrej,

Thank you for your reply! Yes, you are right - I am looking to get the protractor's terminal console itself. I have asked about this in gitter and linked this issue as well. I haven't heard back anything yet. 

I was thinking, if there is a way that we could inject strings from the tests to the report, that could be a decent workaround for now. So, let's say I originally had
`console.log('Start Test: some test - ' + Date.now() )`
if I could replace that with,
`reporter.log('Start Test: some test - ' + Date.now() )`
where the reporter could feed whatever reporter.log injects, I could simple replace my console.log to reporter.log statements when I need it to send it to the report.

I haven't looked deeply into how the reporter currently works, but do you think this is something that could be possible? I guess that depends on protractor itself, what do you think?

Thank you,
Ankit

**Comment by ankitkumarr** [comment]
Hi Andrej,

Another possible workaround could be that instead of doing `console.log`, I could simply write my log in a file and maybe we could add something to your awesome plugin that would pick up the file and display it in text format?

**Comment by ozkar007** [comment]
hi, currently interested in the same utility

**Comment by azachar** [comment]
Hello @ankitkumarr,

Thanks for your effort, it looks promising. All your suggestions make sense. If we won't be able to make   directly with protractor, adding a reporter method `reporter.log` could be an option. 

Anyway, we need a helping hand to make this feature happen. @ankitkumarr could you please drive it? I would be more than happy to review it. @ozkar007 could you help us to implement it, perhaps you could work on visualization.

Architecture wise, the screenshoter is composed with 2 npm plugins, one is grabbing results (this project) and adding them into <UUID>.js files. Then the generated js file is read with html reporter (other plugin) to visualize it.

So what we need to extend both plugins + provide with unit/e2e tests for it.

How does it sound to you?

Cheers,
Andrej

**Comment by ankitkumarr** [comment]
Hi @azachar,

Thank you for your reply! All that sounds great to me. I would love to work on this feature. 

For now, I will add the reporter method `reporter.log` which could write the logs. I would appreciate help with html reporter to visualize the logs screenshoter stores.

Thank you for offering to review, I would love that.

Ankit

**Comment by azachar** [comment]
Hi @ankitkumarr,

thank you for your great contribution. I will review it by the next week. This week I am becoming father ;) 

Cheers,
Andrej

**Comment by ankitkumarr** [comment]
Hi @azachar,

Thank you! No worries at all. And that's awesome :) Congratulations! Best wishes to you and your family.

Ankit

**Comment by azachar** [comment]
Thank you Ankit for your wishes!!!

Closing due to https://github.com/azachar/protractor-screenshoter-plugin/pull/33#issuecomment-354601522
