### ISSUE TITLE
Question- Error installing protractor-screenshoter-plugin in RHEL 7.3 box

### ISSUE THREAD

**Issue by nimishseraphim** [azachar/protractor-screenshoter-plugin#34]
While I am installing the plugin on RHEL 7.3 box, I am getting below error.
Do you have any idea about it.

[root@mo-92cd10a6e tests]# npm install protractor-screenshoter-plugin

> lwip2@1.0.10 install /home/jenkins/workspace/Dummy_tests/tests/node_modules/lwip2
> node lib/install.js

module.js:472
    throw err;
    ^

Error: Cannot find module '/home/jenkins/workspace/Dummy_tests/tests/node_modules/lwip2/lib/install.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:148:9)
    at bootstrap_node.js:542:3
SpotbuyTest@0.0.1 /home/jenkins/workspace/Dummy_tests/tests
└── (empty)

npm WARN SpotbuyTest@0.0.1 No description
npm WARN SpotbuyTest@0.0.1 No repository field.
npm WARN SpotbuyTest@0.0.1 No license field.
npm ERR! Linux 3.10.0-327.10.1.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "protractor-screenshoter-plugin"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! lwip2@1.0.10 install: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lwip2@1.0.10 install script 'node lib/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lwip2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lwip2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lwip2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jenkins/workspace/Dummy_tests/tests/npm-debug.log

**Comment by azachar** [comment]
Hi there, 
it looks like it is a duplicate of https://github.com/azachar/protractor-screenshoter-plugin/issues/29

So simply, try to reinstall your node modules, or simply use ``yarn upgrade``

Cheers,
Andrej
