### ISSUE TITLE
One spec file per page

### ISSUE THREAD

**Issue by frozenbe** [azachar/protractor-screenshoter-plugin#35]
Hello,
I was wondering if it is possible to have each spec file on a separate page in the report?
Currently, pagination is such that the amount of content is even between the pages. But it would be useful to have spec files on separate pages, maybe even links to navigate between them.

**Comment by azachar** [comment]
Hi There,

i think that is great idea, perhaps we could have a tree starting with the spec file and then each node can be a description section... 

i think this needs to be resolved,  do you mind to provide some PR for this?

Cheers,
Andrej

**Comment by azachar** [comment]
This issue was ported to reporter plugin, where it belongs.
