### ISSUE TITLE
Cannot find module 'protractor-screenshoter-plugin'

### ISSUE THREAD

**Issue by anupamdas24** [azachar/protractor-screenshoter-plugin#37]
Getting the below error while running the protractor config file.

[15:53:41] E/launcher - Cannot find module 'protractor-screenshoter-plugin'
[15:53:41] E/launcher - Error: Cannot find module 'protractor-screenshoter-plugin'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Plugins.config.plugins.forEach (/usr/local/lib/node_modules/protractor/built/plugins.js:51:33)
    at Array.forEach (native)
    at new Plugins (/usr/local/lib/node_modules/protractor/built/plugins.js:38:28)
    at Runner.run (/usr/local/lib/node_modules/protractor/built/runner.js:316:39)
    at TaskRunner.run (/usr/local/lib/node_modules/protractor/built/taskRunner.js:109:27)
    at createNextTaskRunner (/usr/local/lib/node_modules/protractor/built/launcher.js:234:28)
[15:53:41] E/launcher - Process exited with error code 199

Config.js :

exports.config = {
  seleniumAddress: 'http://localhost:4444/wd/hub',
  specs: ['test/*spec*.js'],
  framework: 'jasmine',

   plugins: [{
        package: 'protractor-screenshoter-plugin',
        screenshotPath: 'test-result/screenshots',
        screenshotOnExpect: 'failure+success',
        screenshotOnSpec: 'none',
        withLogs: 'true',
        writeReportFreq: 'asap',
        imageToAscii: 'failure',
        clearFoldersBeforeTest: true
    }],

    onPrepare: function() {
        // returning the promise makes protractor wait for the reporter config before executing tests
        return global.browser.getProcessedConfig().then(function(config) {
            //it is ok to be empty
        });
    }

**Comment by codybarr** [comment]
Same issue here

**Comment by codybarr** [comment]
FYI, I fixed this by updating the *package* line in my protractor config:

```
    plugins: [{
        package: 'node_modules/protractor-screenshoter-plugin/index.js',
        screenshotPath: './reports',
        screenshotOnExpect: 'failure+success',
        screenshotOnSpec: 'none',
        withLogs: 'true',
        writeReportFreq: 'asap',
        imageToAscii: 'failure',
        clearFoldersBeforeTest: true
    }],
```

**Comment by kchaitanya863** [comment]
It's only working when installed globally, otherwise it says the title.

**Comment by gtroshin** [comment]
@kchaitanya863 no
you just need to install it via yarn or npm  from your package.json. Not globally, but just for your project  in /node_modules directory.

**Comment by kchaitanya863** [comment]
@gtroshin I did that first, but later when I got an error, installed it globally with,
npm install -g protractor-screenshoter-plugin

**Comment by azachar** [comment]
Hello Guys, try to install the new release 0.4.0 locally that fixed some dependency hell :) Hope it will work flawlessly :)

**Comment by Ciabas** [comment]
Even with version 0.5.0 global installation seems like the only solution here.

**Comment by azachar** [comment]
Hmm, sorry to hear that, anyway it sounds very strange.

Could you please provide a docker image that would demonstrate your issue?

Cheers,
Andrej

**Comment by azachar** [comment]
Btw. where is your protractor? Is it installed globally also? Perhaps this could be the issue.

**Comment by Ciabas** [comment]
Protractor is installed globally also, as suggested here. 
http://www.protractortest.org/#/

**Comment by azachar** [comment]
I would give a shot to install one of the official plugins locally vs globally to see what would be the behavior.  I personally do not use global installation protractor, since i have many projects running different versions.

**Comment by Ciabas** [comment]
It seems that you need global `protractor-screenshoter-plugin` to global `Protractor`. 
Thanks. Consider to mention it in README.

**Comment by azachar** [comment]
Perhaps, you could provide a PR for that :) Would be more than happy to accept it :)

**Comment by brunobastosg** [comment]
Same problem here, but to fix it I had to put `package: '../../../node_modules/protractor-screenshoter-plugin/index.js` instead of `package: 'node_modules/protractor-screenshoter-plugin/index.js'` in my Protractor config file.
