### ISSUE TITLE
Ignored tests result in error being logged due to screenshoter

### ISSUE THREAD

**Issue by TWiStErRob** [azachar/protractor-screenshoter-plugin#55]
> Error in browser instance default while taking the screenshot: logs/reports/screenshots/dd07c0e0-c165-11e7-b4af-bde58b959435.png - Error: Error from waitForAngular: both angularJS testability and angular testability are undefined.  This could be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for details

### Configuration
`"protractor-screenshoter-plugin": "0.3.2",`
```
		{
			package: 'protractor-screenshoter-plugin',
			screenshotPath: 'logs/reports',
			screenshotOnExpect: 'failure',
			screenshotOnSpec: 'failure+success',
			withLogs: 'true',
			writeReportFreq: 'asap',
			clearFoldersBeforeTest: true,
		},
```

Here's two debug sessions to see what state the plugin is in.

### `it` specs disabled with `xdescribe` around them
```
describe('Performances display', function () {
	xdescribe('performances table by film', function () {
		it('shows film headers', function () { ... });
		it('shows cinema headers', function () { ... });
	});
...
```
![image](https://user-images.githubusercontent.com/2906988/32405940-bdfad16e-c166-11e7-8307-4f195e5253e4.png)

### specific `it` spec disabled with `xit`
```
describe('Performances display', function () {
	describe('performances table by film', function () {
		xit('shows film headers', function () { ... });
		it('shows cinema headers', function () { ... });
	});
...
```
![image](https://user-images.githubusercontent.com/2906988/32405960-2cc2b580-c167-11e7-9400-66a220792411.png)

in `protractorUtil.takeScreenshotOnSpecDone`:
```diff
+    if (result.status === 'disabled' || result.status === 'pending') {
+        makeScreenshotsFromEachBrowsers = false;
+    }
    if (makeScreenshotsFromEachBrowsers) {
```
hack confirmed to solve the problem.

Also note there's an API to skip tests: `pending("my reason")`, but in that case the test may have actually started and ready to be screenshot (it could be in the middle of the `it` spec after many `expect`s have passed).

**Comment by azachar** [comment]
Dear @TWiStErRob, 

What a great catch! Sure, this seems to be a bug. I am investigating it now.

**Comment by azachar** [comment]
Hey @TWiStErRob 

I wrote tests for it, but I cannot reproduce it, could you have a look at the branch https://github.com/azachar/protractor-screenshoter-plugin/tree/fix-bug-19?

Cheers,
Andrej

**Comment by TWiStErRob** [comment]
Nice, thank you!
