### ISSUE TITLE
ability to inject additional screens into the report

### ISSUE THREAD

**Issue by tfaron** [azachar/protractor-screenshoter-plugin#58]
We have implemented the plugin but I am curious if there is a way to add addition screenshots to the report. For example if I want to capture a screenshot of a dialog or page so i can use it a reference in the report.

**Comment by azachar** [comment]
Dear @tfaron,

There is no direct feature for that, but I think you can still do it ->

simple add any expect condition and then enable the option

> screenshotOnExpect: 'failure+success',


This will create a screenshot of the page, unfortunately, selenium does not support the whole page screenshot. So only way to see the whole page is scroll + expect to trigger screenshot. 


But if you are interested, you can make such a contribution, have a look here: 

https://github.com/azachar/protractor-screenshoter-plugin/blob/99bc7733e2ba2de4084d5890fe150f1dad4de620/index.js#L67

Cheers,
Andrej
