### ISSUE TITLE
Error while using multiple capabilities in protractor - java.net.BindException: Address already in use: connect

### ISSUE THREAD

**Issue by Galileo1** [azachar/protractor-screenshoter-plugin#62]
Running protractor test with multiple capabilities - chrome & chrome(with mobileEmulation) gives following error 

> [chrome #11] Error in browser instance chrome while taking the raw html: ./REPORTS/e2e/htmls/46702ac0-0277-11e8-a8b6-8f9ba8490823.html - java.net.BindException: Address already in use: connect

Here's the config file -

```
export let config: Config = {
  allScriptsTimeout: 50000,
  getPageTimeout: 50000,
  baseUrl: 'https://someurl.com/',
  framework: 'jasmine2',
  plugins: [{
    package: 'protractor-screenshoter-plugin',
    screenshotPath: './REPORTS/e2e',
    screenshotOnExpect: 'failure+success',
    screenshotOnSpec: 'none',
    withLogs: true,
    writeReportFreq: 'asap',
    imageToAscii: 'none',
    clearFoldersBeforeTest: true
  }],
  multiCapabilities: [{
      browserName: 'chrome',     
      specs: [ '../specs/**/Login.spec.js'],
      chromeOptions : {
        args : ['--no-proxy-server']
      }
    }, {
      specs: [ '../specs/**/Login.spec.js'],
      browserName: 'chrome',
        'chromeOptions': {
            'mobileEmulation': {
                'deviceName': 'Nexus 6P'
        }
      }
  }],
    
  onPrepare: () => {
    browser.manage().window().maximize();
    browser.manage().timeouts().implicitlyWait(timeout.IMPLICIT);
    browser.ignoreSynchronization = true;
    browser.waitForAngularEnabled(false);

    jasmine.getEnv().addReporter(
      new JasmineConsoleReporter({
        colors: 1,           // (0|false)|(1|true)|2
        cleanStack: 1,       // (0|false)|(1|true)|2|3
        verbosity: 4,        // (0|false)|1|2|(3|true)|4
        listStyle: 'indent', // "flat"|"indent"
        activity: false
    }));
     
  },

  jasmineNodeOpts: {
    showColors: true,
    includeStackTrace : true,
    isVerbose : true,
    defaultTimeoutInterval: 2500000
  }
  
};
```

**Comment by azachar** [comment]
Hi there, 
could you please fork this project, and create a new test scenario that fails, have a look at the existing one. 

Without your input, I cannot debug it. 

PS: Just quickly googling come to this issue https://github.com/SeleniumHQ/selenium/issues/4625

Cheers,
Andrej

**Comment by Galileo1** [comment]
Hi @azachar , I forked this project and created bug62.js file. I tried both standalone selenium server and starting a selenium server separately. But could reproduce the issue for some reason. But I am still facing the problem.
![image](https://user-images.githubusercontent.com/9716232/35561016-1183d062-05d5-11e8-97f7-fd1b52734816.png)

**Comment by azachar** [comment]
Hi @Galileo1,
that is a good starting point. Let me check your fork. From your screenshot, it seems to me that you need to modify also a test that will use bug62 config. Have you done that too? That would explain, why you cannot reproduce it.

Cheers,
Andrej

**Comment by azachar** [comment]
Well, your public fork is the same as mine :) Please push your changes..

Here is checklist:

- [ x] create a test config file in https://github.com/azachar/protractor-screenshoter-plugin/blob/master/spec/integrational/protractor-config such bugxxx.js
      *   modify screenshot path `.tmp/bug55`
      *   pick a spec to test or keep the same like in `bug55.js`
- [ ]   duplicate a whole `describe` section from https://github.com/azachar/protractor-screenshoter-plugin/blob/f6bded9639ddb80a5855270910b2961de74e4011/spec/integrational/screenshoter.int.spec.js#L1280
     * modify path to the reporter
https://github.com/azachar/protractor-screenshoter-plugin/blob/f6bded9639ddb80a5855270910b2961de74e4011/spec/integrational/screenshoter.int.spec.js#L1282

     * modify test according to your expectations, in this case, we expected that there will be no protractor errors (thus `toBeTruthy()`). If your protractor test should fail instead, then modify expectation to `toBeFalsy()`
- [ ] run that test, when it fails, push your changes to your fork, so we can look at your problem and reproduce it.

**Comment by kenlacoste843** [comment]
Have the same issue..

**Comment by azachar** [comment]
Perhaps have a look at your apps that occupying your port with `ls -i :<your-port-number>`

**Comment by azachar** [comment]
Since no more report, I guess it is resolved on your end. Please reopen if you believe it is on my end.

**Comment by Xfaramir** [comment]
probably you're using the vs code debugger to run the protractor test. Instead use just the command 
protractor protractor.conf.js . and it should work also make sure to add maxSessions: 2 to run it in parallel
