### ISSUE TITLE
Getting 'Error in browser instance X while taking the logs' for each test in Firefox and Safari

### ISSUE THREAD

**Issue by codybarr** [azachar/protractor-screenshoter-plugin#66]
Bug report
---
- Your protractor configuration file (attached in next comment)
- Protractor Version: `5.3.0`
- Browser(s): `Safari` and `Firefox`
- Node Version: `8.9.4`
- Angular Version: `NA`
- Operating System and Version `OSX 10.11.6`
- Output from running the test
```
[$] protractor ./bug66.conf.js --browser=safari
(node:77133) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[09:00:05] I/launcher - Running 1 instances of WebDriver
[09:00:05] I/local - Starting selenium standalone server...
[09:00:06] I/local - Selenium standalone server started at http://192.168.1.92:53762/wd/hub
Activated Protractor Screenshoter Plugin, ver. 0.10.1 (c) 2016 - 2018 Andrej Zachar and contributors
Started
Creating reporter at .tmp/bug66/
Error in browser instance safari while taking the logs:The command 'POST /session/D11C1BD4-41CD-48D2-BB9F-CE956C6951CF/log' is not implemented.
.

1 spec, 0 failures
Finished in 2.227 seconds
```

---
When running my tests in Chrome I don't ever receive the 'Error in browser instance X while taking the logs' in my console output. But I'm getting the error for every single test I run in Firefox and Safari:

![image](https://user-images.githubusercontent.com/4359586/36674837-4478af14-1ad5-11e8-8b8b-a1f46439f0b5.png)

Steps to reproduce:
- Run the spec, Chrome will be used in directConnect mode. Observe that the error in question does not display.
- Run the spec again but specify `--browser=firefox/safari`. Observe error in question. (note if you specify safari just comment out the `directConnect: true` line in the config.

I'm not sure this is causing an actual problem - my console output just gets really messy:

![image](https://user-images.githubusercontent.com/4359586/36675089-06581160-1ad6-11e8-82f7-e345ab13d2e8.png)

I'll attach the spec and config file after I get the issue #.

**Comment by codybarr** [comment]
Here's the spec/config:

[bug66.zip](https://github.com/azachar/protractor-screenshoter-plugin/files/1758915/bug66.zip)

**Comment by azachar** [comment]
Hello @codybarr,

Thank you for your detailed message, unfortunately Safari nor Firefox do not support grabbing console logs as far as I know. It works fine only in google chrome. So perhaps, if there will be support from Safari or Firefox, we can re-open this issue.

Anyway, thank you for your bug report!

Cheers,
Andrej

**Comment by codybarr** [comment]
@azachar Can we turn that error logging off for Firefox and Safari then?

**Comment by azachar** [comment]
@codybarr Make sense, do you mind to provide such PR? Thank you!

**Comment by azachar** [comment]
Perhaps we could even shown warning once, that firefox and safari doens't support console logs yet :)
