### ISSUE TITLE
TypeError: imageToAscii is not a function

### ISSUE THREAD

**Issue by amiteshCoder** [azachar/protractor-screenshoter-plugin#77]
Hi there!

Bug report
---
- Your protractor configuration file
- Protractor Version: `5.3.2`
- Browser(s): `Chrome`
- Node Version: `v10.11.0`
- Angular Version: ``
- Operating System and Version `Mac OS`
I am using **protractor-screenshoter-plugin** reporter for my protractor setup. But When I run my tests. I get the following error:

**TypeError: imageToAscii is not a function
    at /usr/local/lib/node_modules/protractor-screenshoter-plugin/index.js:216:13
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/protractor-screenshoter-plugin/index.js:101:9)
    at WriteStream.emit (events.js:182:13)
    at finishMaybe (_stream_writable.js:641:14)
    at stream._final (_stream_writable.js:619:5)
    at WriteStream._final (internal/fs/streams.js:264:3)
    at callFinal (_stream_writable.js:612:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Please check the installation at https://github.com/IonicaBizau/image-to-ascii/blob/master/INSTALLATION.md**

Following is the configuration I am using:

 **package: 'protractor-screenshoter-plugin',
        screenshotPath: './end-to-end-test/REPORTS/e2e',
        screenshotOnExpect: 'failure',
        screenshotOnSpec: 'failure',
        htmlOnExpect: 'failure+success',
        htmlOnSpec:'failure+success',
        withLogs: true,
        htmlReport: true,
        screenshotPath: './end-to-end-test/REPORTS/e2e/screenshots',
        writeReportFreq: 'asap',
        verbose: 'debug',
        imageToAscii: 'failure+success',
        clearFoldersBeforeTest: true,**

Any idea why I am getting this error. Thanks in advance.

**Comment by azachar** [comment]
Dear @amiteshCoder,

Thank you for reaching me out. 

You need to 
1. either install the optional dependencies for **imageToAscii** option, then please follow https://github.com/azachar/protractor-screenshoter-plugin#how-to-install

2. or remove completely the line with  `imageToAscii: 'failure+success',` from your configuration file.

Cheers,
Andrej
