### ISSUE TITLE
Support for Jenkins

### ISSUE THREAD

**Issue by bsrikan** [azachar/protractor-screenshoter-plugin#80]
Feature Request
---

I really like everything about this reporter. My tests run in Jenkins and the html report pulls up a blank screen. Will be great if we can get the report displayed in Jenkins.

Thanks!!

**Comment by azachar** [comment]
Dear @bsrikan, 

Thank you for reaching me out. 

Currently, I am too busy to help out with Jenkins, but for curiosity, could you share your screen and Jenkins + this plugin configuration that produces that blank page? Perhaps there are some access issues.

Anyway, hope that one could help!

Best regards,
Andrej

**Comment by barrynorman** [comment]
@bsrikan did you take a look at the console? Jenkins is usually blocking inline-scripts and other related stuff, e.g. css, fonts. With `publishHtml` you can easily "export" your report. But maybe this link will help you with your "problem" https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy

**Comment by bsrikan** [comment]
Thanks for the pointer and help. Looking into it with our devops team.

**Comment by bsrikan** [comment]
Adding this to Jenkins Script console fixed it. System.setProperty("hudson.model.DirectoryBrowserSupport.CSP", "")
